project_id = "ddbfmgqknjggkokyfmzz"

[functions.cleanup-announcements]
verify_jwt = false

[functions.aya-chat]
verify_jwt = false

[functions.verify-student-email]
verify_jwt = false

[functions.confirm-student-email]
verify_jwt = false

[functions.city-resources]
verify_jwt = false
